runs:
  using: composite
  steps:
    - name: Install Zrok
      shell: bash
      run: |
        curl -L -O https://github.com/openziti/zrok/releases/download/v1.0.4/zrok_1.0.4_linux_amd64.tar.gz
        mkdir /tmp/zrok && tar xvzf ./zrok_1.0.4_linux_amd64.tar.gz -C /tmp/zrok
        mkdir -p /usr/local/bin && install /tmp/zrok/zrok /usr/local/bin/
        zrok version
        zrok config set apiEndpoint ${{ secrets.SW_ZROK_API_ENDPOINT }}
        zrok enable ${{ secrets.SW_ZROK_TOKEN }} --headless
