kind: pipeline
name: default

steps:
  - name: test
    image: node:16-alpine
    commands:
      - npm install
      - npm run build
      - npm test

  - name: e2e-tests
    image: node:16-alpine
    commands:
      - npm install
      - npm run build
      - npm run -w=@sw-internal/e2e-realtime-api dev
    environment:
      API_HOST:
        from_secret: API_HOST
      RELAY_HOST:
        from_secret: RELAY_HOST
      RELAY_PROJECT:
        from_secret: RELAY_PROJECT
      RELAY_TOKEN:
        from_secret: RELAY_TOKEN
      RELAY_CONTEXT:
        from_secret: RELAY_CONTEXT
      RELAY_FROM_NUMBER:
        from_secret: RELAY_FROM_NUMBER
      RELAY_TO_NUMBER:
        from_secret: RELAY_TO_NUMBER
      # Scoped value for Voice tests
      VOICE_HOST:
        from_secret: VOICE_HOST
      VOICE_PROJECT:
        from_secret: VOICE_PROJECT
      VOICE_TOKEN:
        from_secret: VOICE_TOKEN
      VOICE_CONTEXT:
        from_secret: VOICE_CONTEXT
      VOICE_DIAL_FROM_NUMBER:
        from_secret: VOICE_DIAL_FROM_NUMBER
      VOICE_DIAL_TO_NUMBER:
        from_secret: VOICE_DIAL_TO_NUMBER
      VOICE_DIAL_CONNECT_TO_NUMBER:
        from_secret: VOICE_DIAL_CONNECT_TO_NUMBER

trigger:
  event: push
