name: Install
description: Install dependencies for the monorepo

inputs:
  NODE_VERSION:
    required: false
    default: 20.x
    description: Node version to use

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: npm
    - name: Cache node_modules
      id: cache_node_modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-node-modules-${{ inputs.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        path: |
          node_modules
          packages/*/node_modules
          scripts/*/node_modules
          internal/*/node_modules
    - if: steps.cache_node_modules.outputs.cache-hit != 'true'
      name: Install Dependencies
      shell: bash
      run: npm ci
