name: Report Test Results
description: Report the status of test runs

inputs:
  result:
    required: true
    type: string
    description: Result of the test job
  test-suite:
    required: true
    type: string
    description: Name of the test suite reporting results for

runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
      shell: bash
    - name: Dump runner context
      run: echo '${{ toJSON(runner) }}'
      shell: bash
    - name: Dump env context
      run: echo '${{ toJSON(env) }}'
      shell: bash
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
      shell: bash
    - run: echo Status for ${{ inputss.test-suite }} ${{ inputs.result }}
      shell: bash
