name: Report Test Results
description: Report the status of test runs

inputs:
  result:
    required: true
    type: string
    description: Result of the test job
  test-suite:
    required: true
    type: string
    description: Name of the test suite reporting results for
  environment:
    required: true
    type: string
  statsd-host:
    required: true
    type: string
  statsd-port:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # - name: Dump GitHub context
    #   run: echo '${{ toJSON(github) }}'
    #   shell: bash
    - run: echo input workflow ${{ inputs.test-suite }}
      shell: bash
    - run: echo input result ${{ inputs.result }}
      shell: bash
    - run: echo github workflow ${{ github.workflow }}
      shell: bash
    - run: echo github job ${{ github.job }}
      shell: bash
    - run: echo job Status ${{ job.status }}
      shell: bash
    - id: check_result
      shell: bash
      run: |
        if [[ "${{ inputs.result }}" == "success" ]]; then
          echo "RESULT=1" >> "$GITHUB_OUTPUT"
        else
          echo "RESULT=0" >> "$GITHUB_OUTPUT"
        fi
    - run: echo "monitoring.checks.e2e.result,|#repo=signalwire-js,workflow=${{ inputs.test-suite }},environment=${{ inputs.environment }}:${{steps.check_result.outputs.RESULT}}|g" | nc -w 1 -u ${{ inputs.statsd-host }} ${{ inputs.statsd-port }}
      shell: bash
