name: Report Test Results
description: Report the status of test runs

inputs:
  result:
    required: true
    type: string
    description: Result of the test job
  test-suite:
    required: true
    type: string
    description: Name of the test suite reporting results for
  environment:
    required: true
    type: string
  statsd-host:
    required: true
    type: string
  statsd-port:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # - name: Dump GitHub context
    #   run: echo '${{ toJSON(github) }}'
    #   shell: bash
    - run: echo input workflow ${{ inputs.test-suite }}
      shell: bash
    - run: echo input result ${{ inputs.result }}
      shell: bash
    - run: echo github workflow ${{ github.workflow }}
      shell: bash
    - run: echo github job ${{ github.job }}
      shell: bash
    - run: echo job status ${{ job.status }}
      shell: bash
    - id: check_result
      shell: bash
      run: |
        if [[ "${{ inputs.result }}" == "success" ]]; then
          echo "RESULT=1" >> "$GITHUB_OUTPUT"
        else
          echo "RESULT=0" >> "$GITHUB_OUTPUT"
        fi
    - name: Check if Telegraf is installed
      shell: bash
      run: |
        if ! dpkg -l | grep telegraf; then
          echo "Telegraf is not installed!"
        else
          echo "Telegraf is installed!"
        fi
    - name: Check if Telegraf is installed
      shell: bash
      run: |
        if ! which telegraf; then
          echo "Telegraf is not installed!"
        else
          echo "Telegraf is installed!"
        fi
    - name: Install Telegraf
      shell: bash
      run: |
        # influxdata-archive_compat.key GPG Fingerprint: 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E
        wget -q https://repos.influxdata.com/influxdata-archive_compat.key
        echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
        echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
        sudo apt-get update && sudo apt-get install telegraf
    - name: Setup Telegraf configuration
      shell: bash
      run: |
        telegraf config > telegraf.conf
    - name: Check Telegraf status
      shell: bash
      run: |
        systemctl status telegraf.service

    # - name: Start Telegraf
    #   shell: bash
    #   run: |
    #     systemctl start telegraf
    # - name: Test Telegraf
    #   shell: bash
    #   run: |
    #     telegraf --config telegraf.conf --test
