name: Report Test Results
description: Report the status of test runs

inputs:
  result:
    required: true
    type: string
    description: Result of the test job
  test-suite:
    required: true
    type: string
    description: Name of the test suite reporting results for
  statsd-host:
    required: true
    type: string
  statsd-port:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
      shell: bash
    - run: echo Status for workflow ${{ inputs.test-suite }} input result ${{ inputs.result }}
      shell: bash

# github.job "e2e-tests"
# github.workflow "Unit and stack tests"
# {{ job.status }} success|failure
# conclusion

statsd guage
tag status:${status}`
tag test-suite
