name: Report Test Results
description: Report the status of test runs

inputs:
  result:
    required: true
    type: string
    description: Result of the test job
  test-suite:
    required: true
    type: string
    description: Name of the test suite reporting results for
  environment:
    required: true
    type: string
  influxdb-bucket:
    required: true
    type: string
  influxdb-org:
    required: true
    type: string
  influxdb-token:
    required: true
    type: string
  influxdb-url:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # - name: Dump GitHub context
    #   run: echo '${{ toJSON(github) }}'
    #   shell: bash
    - run: echo input workflow ${{ inputs.test-suite }}
      shell: bash
    - run: echo input result ${{ inputs.result }}
      shell: bash
    - run: echo github workflow ${{ github.workflow }}
      shell: bash
    - run: echo github job ${{ github.job }}
      shell: bash
    - run: echo job status ${{ job.status }}
      shell: bash
    - id: check_result
      shell: bash
      run: |
        if [[ "${{ inputs.result }}" == "success" ]]; then
          echo "RESULT=1" >> "$GITHUB_OUTPUT"
        else
          echo "RESULT=0" >> "$GITHUB_OUTPUT"
        fi
    - name: curl
      shell: bash
      run: |
        curl -V
    - name: send result
      shell: bash
      run: |
        curl --request POST \
        "${{ inputs.influxdb-url }}/api/v2/write?org=${{ inputs.influxdb-org }}&bucket=${{ inputs.influxdb-bucket }}&precision=ns" \
          --header "Authorization: Token ${{ inputs.influxdb-token }}" \
          --header "Content-Type: text/plain; charset=utf-8" \
          --header "Accept: application/json" \
          --data-binary '
            airSensors,sensor_id=TLM0201 temperature=73.97038159354763,humidity=35.23103248356096,co=0.48445310567793615 1630424257000000000
            airSensors,sensor_id=TLM0202 temperature=75.30007505999716,humidity=35.651929918691714,co=0.5141876544505826 1630424257000000000
          '
