name: RealtimeAPI SDK [production euswcom]

on:
  push:
    branches:
      - 'min/run-only-video-test'
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '30 */4 * * *' # "At minute 30 past every 4th hour"

concurrency:
  group: ${{ github.workflow }}-realtime-api-production-eu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        uses: ./.github/actions/install
        with:
          NODE_VERSION: ${{ matrix.node-version }}
      - name: Build SDKs
        uses: ./.github/actions/build
        with:
          NODE_VERSION: ${{ matrix.node-version }}
      - name: Install Playwright
        uses: ./.github/actions/playwright
        with:
          PLAYWRIGHT_VERSION: '1.35.1' # TODO: Read from deps ?
      - name: Test
        id: run-tests
        run: npm run -w=@sw-internal/e2e-realtime-api dev:playwright
        env:
          SW_TEST_CONFIG: |
            '{
              "ignoreFiles": [
                "chat.test.ts",
                "messaging.test.ts",
                "pubSub.test.ts",
                "task.test.ts",
                "utils.test.ts",
                "voice.test.ts",
                "voicePass.test.ts",
                "voiceTapAllListeners.test.ts",
                "playwright/videoHandRaise.test.ts"
              ],
              "ignoreDirectories": ["voiceCollect", "voiceDetect", "voicePlayback", "voicePrompt", "voiceRecord"],
              "env": {
                  "API_HOST": "ops.eu-signalwire.com",
                  "RELAY_HOST": "relay.eu-signalwire.com",
                  "RELAY_PROJECT": "07bbb6ca-07cb-410d-88a7-a3184afb3677",
                  "RELAY_TOKEN": "${{ fromJSON(secrets.PRODUCTION_EUSWCOM_E2E_REALTIME_SW_TEST_CONFIG).env.RELAY_TOKEN }}",
                  "DAPP_DOMAIN": "dapp.eu-signalwire.com",
                  "PLAYBACK_URL": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
              }
            }'
      - name: Report Result
        if: success() || failure()
        uses: ./.github/actions/report-test-result
        with:
          result: ${{ steps.run-tests.conclusion }}
          test-suite: realtime-api
          environment: production-euswcom
          influxdb-bucket: ${{ secrets.INFLUXDB_BUCKET }}
          influxdb-org: ${{ secrets.INFLUXDB_ORG }}
          influxdb-token: ${{ secrets.INFLUXDB_TOKEN }}
          influxdb-url: ${{ secrets.INFLUXDB_URL }}
